// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateCompany(ctx context.Context, name string) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, name)
	var i Company
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at
`

type CreateCustomerParams struct {
	CompanyID          int64          `json:"company_id"`
	FirstName          string         `json:"first_name"`
	LastName           string         `json:"last_name"`
	Email              sql.NullString `json:"email"`
	Phone              sql.NullString `json:"phone"`
	MedicalAidProvider sql.NullString `json:"medical_aid_provider"`
	MedicalAidNumber   sql.NullString `json:"medical_aid_number"`
	MedicalPlan        sql.NullString `json:"medical_plan"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.CompanyID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.MedicalAidProvider,
		arg.MedicalAidNumber,
		arg.MedicalPlan,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomerPremium = `-- name: CreateCustomerPremium :one
INSERT INTO customer_premiums (customer_id, premium_amount, effective_date)
VALUES (?, ?, ?) RETURNING id, customer_id, premium_amount, effective_date, created_at
`

type CreateCustomerPremiumParams struct {
	CustomerID    int64     `json:"customer_id"`
	PremiumAmount float64   `json:"premium_amount"`
	EffectiveDate time.Time `json:"effective_date"`
}

func (q *Queries) CreateCustomerPremium(ctx context.Context, arg CreateCustomerPremiumParams) (CustomerPremium, error) {
	row := q.db.QueryRowContext(ctx, createCustomerPremium, arg.CustomerID, arg.PremiumAmount, arg.EffectiveDate)
	var i CustomerPremium
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.PremiumAmount,
		&i.EffectiveDate,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?) RETURNING id, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, firstname, lastname, agent_id, company_id)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, email, password_hash, firstname, lastname, agent_id, company_id, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	AgentID      string `json:"agent_id"`
	CompanyID    int64  `json:"company_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Firstname,
		arg.Lastname,
		arg.AgentID,
		arg.CompanyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getAllCompanies = `-- name: GetAllCompanies :many
SELECT id, name, created_at FROM companies ORDER BY created_at DESC
`

func (q *Queries) GetAllCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers ORDER BY created_at DESC
`

func (q *Queries) GetAllCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.MedicalAidProvider,
			&i.MedicalAidNumber,
			&i.MedicalPlan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, created_at FROM companies WHERE id = ?
`

func (q *Queries) GetCompany(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE email = ?
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email sql.NullString) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one

SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE id = ?
`

// -----------------------
// Customer Queries
// -----------------------
func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE phone = ?
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone sql.NullString) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerPremiumsByCustomerID = `-- name: GetCustomerPremiumsByCustomerID :many

SELECT id, customer_id, premium_amount, effective_date, created_at FROM customer_premiums WHERE customer_id = ? ORDER BY effective_date DESC
`

// -----------------------
// Customer Premium Queries
// -----------------------
func (q *Queries) GetCustomerPremiumsByCustomerID(ctx context.Context, customerID int64) ([]CustomerPremium, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerPremiumsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerPremium{}
	for rows.Next() {
		var i CustomerPremium
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PremiumAmount,
			&i.EffectiveDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByAgentID = `-- name: GetUserByAgentID :one
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, created_at FROM users WHERE agent_id = ?
`

func (q *Queries) GetUserByAgentID(ctx context.Context, agentID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAgentID, agentID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, created_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.CreatedAt,
	)
	return i, err
}
