// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countRecentOTPAttempts = `-- name: CountRecentOTPAttempts :one
SELECT COUNT(*) as count FROM otp_codes
WHERE email = ? AND created_at > DATE_SUB(NOW(), INTERVAL 15 MINUTE)
`

func (q *Queries) CountRecentOTPAttempts(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentOTPAttempts, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentStatus = `-- name: CreateAgentStatus :execresult
INSERT INTO agent_status (user_id, status)
VALUES (?, ?)
`

type CreateAgentStatusParams struct {
	UserID int32  `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) CreateAgentStatus(ctx context.Context, arg CreateAgentStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAgentStatus, arg.UserID, arg.Status)
}

const createCallRecord = `-- name: CreateCallRecord :execresult

INSERT INTO transcriptions (
    customer_id, agent_id, company_id, call_sid, from_number,
    to_number, call_status, duration, recording_start_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCallRecordParams struct {
	CustomerID         sql.NullInt32  `json:"customer_id"`
	AgentID            sql.NullInt32  `json:"agent_id"`
	CompanyID          int32          `json:"company_id"`
	CallSid            string         `json:"call_sid"`
	FromNumber         sql.NullString `json:"from_number"`
	ToNumber           sql.NullString `json:"to_number"`
	CallStatus         sql.NullString `json:"call_status"`
	Duration           sql.NullInt32  `json:"duration"`
	RecordingStartTime sql.NullTime   `json:"recording_start_time"`
}

// -----------------------
// Call/Transcription Queries
// -----------------------
func (q *Queries) CreateCallRecord(ctx context.Context, arg CreateCallRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCallRecord,
		arg.CustomerID,
		arg.AgentID,
		arg.CompanyID,
		arg.CallSid,
		arg.FromNumber,
		arg.ToNumber,
		arg.CallStatus,
		arg.Duration,
		arg.RecordingStartTime,
	)
}

const createCompany = `-- name: CreateCompany :execresult
INSERT INTO companies (name) VALUES (?)
`

func (q *Queries) CreateCompany(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCompany, name)
}

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customers (company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCustomerParams struct {
	CompanyID          int32          `json:"company_id"`
	FirstName          string         `json:"first_name"`
	LastName           string         `json:"last_name"`
	Email              sql.NullString `json:"email"`
	Phone              sql.NullString `json:"phone"`
	MedicalAidProvider sql.NullString `json:"medical_aid_provider"`
	MedicalAidNumber   sql.NullString `json:"medical_aid_number"`
	MedicalPlan        sql.NullString `json:"medical_plan"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer,
		arg.CompanyID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.MedicalAidProvider,
		arg.MedicalAidNumber,
		arg.MedicalPlan,
	)
}

const createCustomerPremium = `-- name: CreateCustomerPremium :execresult
INSERT INTO customer_premiums (customer_id, premium_amount, effective_date)
VALUES (?, ?, ?)
`

type CreateCustomerPremiumParams struct {
	CustomerID    int32     `json:"customer_id"`
	PremiumAmount string    `json:"premium_amount"`
	EffectiveDate time.Time `json:"effective_date"`
}

func (q *Queries) CreateCustomerPremium(ctx context.Context, arg CreateCustomerPremiumParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomerPremium, arg.CustomerID, arg.PremiumAmount, arg.EffectiveDate)
}

const createOTPCode = `-- name: CreateOTPCode :execresult

INSERT INTO otp_codes (email, otp_code, expires_at)
VALUES (?, ?, ?)
`

type CreateOTPCodeParams struct {
	Email     string    `json:"email"`
	OtpCode   string    `json:"otp_code"`
	ExpiresAt time.Time `json:"expires_at"`
}

// -----------------------
// OTP Code Queries
// -----------------------
func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOTPCode, arg.Email, arg.OtpCode, arg.ExpiresAt)
}

const createQueueEntry = `-- name: CreateQueueEntry :execresult

INSERT INTO call_queue (call_sid, company_id, from_number, to_number, status, agents_tried)
VALUES (?, ?, ?, ?, 'waiting', '[]')
`

type CreateQueueEntryParams struct {
	CallSid    string `json:"call_sid"`
	CompanyID  int32  `json:"company_id"`
	FromNumber string `json:"from_number"`
	ToNumber   string `json:"to_number"`
}

// -----------------------
// Call Queue Queries
// -----------------------
func (q *Queries) CreateQueueEntry(ctx context.Context, arg CreateQueueEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createQueueEntry,
		arg.CallSid,
		arg.CompanyID,
		arg.FromNumber,
		arg.ToNumber,
	)
}

const createSession = `-- name: CreateSession :execresult
INSERT INTO sessions (id, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    int32     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
}

const createTask = `-- name: CreateTask :execresult

INSERT INTO tasks (assigned_to, customer_id, call_id, title, description, type, status, due_date)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	AssignedTo  int32          `json:"assigned_to"`
	CustomerID  sql.NullInt32  `json:"customer_id"`
	CallID      sql.NullInt32  `json:"call_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Type        sql.NullString `json:"type"`
	Status      sql.NullString `json:"status"`
	DueDate     sql.NullTime   `json:"due_date"`
}

// -----------------------
// Task Queries
// -----------------------
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.AssignedTo,
		arg.CustomerID,
		arg.CallID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.DueDate,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (email, password_hash, firstname, lastname, agent_id, company_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	AgentID      string `json:"agent_id"`
	CompanyID    int32  `json:"company_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Firstname,
		arg.Lastname,
		arg.AgentID,
		arg.CompanyID,
	)
}

const deleteExpiredOTPCodes = `-- name: DeleteExpiredOTPCodes :exec
DELETE FROM otp_codes WHERE expires_at < NOW() OR used = 1
`

func (q *Queries) DeleteExpiredOTPCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOTPCodes)
	return err
}

const deleteQueueEntry = `-- name: DeleteQueueEntry :exec
DELETE FROM call_queue WHERE call_sid = ?
`

func (q *Queries) DeleteQueueEntry(ctx context.Context, callSid string) error {
	_, err := q.db.ExecContext(ctx, deleteQueueEntry, callSid)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getAgentCallHistory = `-- name: GetAgentCallHistory :many
SELECT id, customer_id, agent_id, company_id, call_sid, recording_sid, recording_url, recording_duration, recording_status, recording_channels, recording_start_time, transcript, summary, from_number, to_number, call_status, duration, call_reason, transcription_text, created_at FROM transcriptions
WHERE agent_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetAgentCallHistoryParams struct {
	AgentID sql.NullInt32 `json:"agent_id"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
}

func (q *Queries) GetAgentCallHistory(ctx context.Context, arg GetAgentCallHistoryParams) ([]Transcription, error) {
	rows, err := q.db.QueryContext(ctx, getAgentCallHistory, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcription{}
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.AgentID,
			&i.CompanyID,
			&i.CallSid,
			&i.RecordingSid,
			&i.RecordingUrl,
			&i.RecordingDuration,
			&i.RecordingStatus,
			&i.RecordingChannels,
			&i.RecordingStartTime,
			&i.Transcript,
			&i.Summary,
			&i.FromNumber,
			&i.ToNumber,
			&i.CallStatus,
			&i.Duration,
			&i.CallReason,
			&i.TranscriptionText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCompanies = `-- name: GetAllCompanies :many
SELECT id, name, created_at FROM companies ORDER BY created_at DESC
`

func (q *Queries) GetAllCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, getAllCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCustomers = `-- name: GetAllCustomers :many
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers ORDER BY created_at DESC
`

func (q *Queries) GetAllCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.MedicalAidProvider,
			&i.MedicalAidNumber,
			&i.MedicalPlan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersByCompany = `-- name: GetAllUsersByCompany :many
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, last_call_ended_at, created_at FROM users WHERE company_id = ? ORDER BY id ASC
`

func (q *Queries) GetAllUsersByCompany(ctx context.Context, companyID int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Firstname,
			&i.Lastname,
			&i.AgentID,
			&i.CompanyID,
			&i.LastCallEndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableAgentsByCompanyLongestIdle = `-- name: GetAvailableAgentsByCompanyLongestIdle :many

SELECT u.id, u.agent_id, u.firstname, u.lastname, u.company_id, u.last_call_ended_at
FROM users u
INNER JOIN (
    SELECT user_id, MAX(created_at) as latest_status_time
    FROM agent_status
    GROUP BY user_id
) latest_status ON u.id = latest_status.user_id
INNER JOIN agent_status ast ON u.id = ast.user_id
    AND ast.created_at = latest_status.latest_status_time
WHERE u.company_id = ?
    AND ast.status = 'available'
ORDER BY COALESCE(u.last_call_ended_at, '1970-01-01 00:00:00') ASC, u.id ASC
`

type GetAvailableAgentsByCompanyLongestIdleRow struct {
	ID              int32        `json:"id"`
	AgentID         string       `json:"agent_id"`
	Firstname       string       `json:"firstname"`
	Lastname        string       `json:"lastname"`
	CompanyID       int32        `json:"company_id"`
	LastCallEndedAt sql.NullTime `json:"last_call_ended_at"`
}

// -----------------------
// Sequential Call Routing Queries
// -----------------------
func (q *Queries) GetAvailableAgentsByCompanyLongestIdle(ctx context.Context, companyID int32) ([]GetAvailableAgentsByCompanyLongestIdleRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableAgentsByCompanyLongestIdle, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAvailableAgentsByCompanyLongestIdleRow{}
	for rows.Next() {
		var i GetAvailableAgentsByCompanyLongestIdleRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Firstname,
			&i.Lastname,
			&i.CompanyID,
			&i.LastCallEndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallBySid = `-- name: GetCallBySid :one
SELECT id, customer_id, agent_id, company_id, call_sid, recording_sid, recording_url, recording_duration, recording_status, recording_channels, recording_start_time, transcript, summary, from_number, to_number, call_status, duration, call_reason, transcription_text, created_at FROM transcriptions WHERE call_sid = ?
`

func (q *Queries) GetCallBySid(ctx context.Context, callSid string) (Transcription, error) {
	row := q.db.QueryRowContext(ctx, getCallBySid, callSid)
	var i Transcription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AgentID,
		&i.CompanyID,
		&i.CallSid,
		&i.RecordingSid,
		&i.RecordingUrl,
		&i.RecordingDuration,
		&i.RecordingStatus,
		&i.RecordingChannels,
		&i.RecordingStartTime,
		&i.Transcript,
		&i.Summary,
		&i.FromNumber,
		&i.ToNumber,
		&i.CallStatus,
		&i.Duration,
		&i.CallReason,
		&i.TranscriptionText,
		&i.CreatedAt,
	)
	return i, err
}

const getCallsByCustomer = `-- name: GetCallsByCustomer :many
SELECT id, customer_id, agent_id, company_id, call_sid, recording_sid, recording_url, recording_duration, recording_status, recording_channels, recording_start_time, transcript, summary, from_number, to_number, call_status, duration, call_reason, transcription_text, created_at FROM transcriptions
WHERE customer_id = ?
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) GetCallsByCustomer(ctx context.Context, customerID sql.NullInt32) ([]Transcription, error) {
	rows, err := q.db.QueryContext(ctx, getCallsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcription{}
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.AgentID,
			&i.CompanyID,
			&i.CallSid,
			&i.RecordingSid,
			&i.RecordingUrl,
			&i.RecordingDuration,
			&i.RecordingStatus,
			&i.RecordingChannels,
			&i.RecordingStartTime,
			&i.Transcript,
			&i.Summary,
			&i.FromNumber,
			&i.ToNumber,
			&i.CallStatus,
			&i.Duration,
			&i.CallReason,
			&i.TranscriptionText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallsByPhone = `-- name: GetCallsByPhone :many
SELECT id, customer_id, agent_id, company_id, call_sid, recording_sid, recording_url, recording_duration, recording_status, recording_channels, recording_start_time, transcript, summary, from_number, to_number, call_status, duration, call_reason, transcription_text, created_at FROM transcriptions
WHERE from_number = ? OR to_number = ?
ORDER BY created_at DESC
LIMIT 20
`

type GetCallsByPhoneParams struct {
	FromNumber sql.NullString `json:"from_number"`
	ToNumber   sql.NullString `json:"to_number"`
}

func (q *Queries) GetCallsByPhone(ctx context.Context, arg GetCallsByPhoneParams) ([]Transcription, error) {
	rows, err := q.db.QueryContext(ctx, getCallsByPhone, arg.FromNumber, arg.ToNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcription{}
	for rows.Next() {
		var i Transcription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.AgentID,
			&i.CompanyID,
			&i.CallSid,
			&i.RecordingSid,
			&i.RecordingUrl,
			&i.RecordingDuration,
			&i.RecordingStatus,
			&i.RecordingChannels,
			&i.RecordingStartTime,
			&i.Transcript,
			&i.Summary,
			&i.FromNumber,
			&i.ToNumber,
			&i.CallStatus,
			&i.Duration,
			&i.CallReason,
			&i.TranscriptionText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, created_at FROM companies WHERE id = ?
`

func (q *Queries) GetCompany(ctx context.Context, id int32) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE email = ?
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email sql.NullString) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one

SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE id = ?
`

// -----------------------
// Customer Queries
// -----------------------
func (q *Queries) GetCustomerByID(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE phone = ?
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone sql.NullString) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.MedicalAidProvider,
		&i.MedicalAidNumber,
		&i.MedicalPlan,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerPremiumsByCustomerID = `-- name: GetCustomerPremiumsByCustomerID :many

SELECT id, customer_id, premium_amount, effective_date, created_at FROM customer_premiums WHERE customer_id = ? ORDER BY effective_date DESC
`

// -----------------------
// Customer Premium Queries
// -----------------------
func (q *Queries) GetCustomerPremiumsByCustomerID(ctx context.Context, customerID int32) ([]CustomerPremium, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerPremiumsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerPremium{}
	for rows.Next() {
		var i CustomerPremium
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.PremiumAmount,
			&i.EffectiveDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomersByCompany = `-- name: GetCustomersByCompany :many
SELECT id, company_id, first_name, last_name, email, phone, medical_aid_provider, medical_aid_number, medical_plan, created_at FROM customers WHERE company_id = ? ORDER BY first_name ASC, last_name ASC
`

func (q *Queries) GetCustomersByCompany(ctx context.Context, companyID int32) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.MedicalAidProvider,
			&i.MedicalAidNumber,
			&i.MedicalPlan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAgentStatus = `-- name: GetLatestAgentStatus :one

SELECT id, user_id, status, created_at FROM agent_status
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 1
`

// -----------------------
// Agent Status Queries
// -----------------------
func (q *Queries) GetLatestAgentStatus(ctx context.Context, userID int32) (AgentStatus, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentStatus, userID)
	var i AgentStatus
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOldestWaitingCall = `-- name: GetOldestWaitingCall :one
SELECT id, call_sid, company_id, from_number, to_number, status, current_agent_index, agents_tried, created_at, updated_at FROM call_queue
WHERE company_id = ? AND status = 'waiting'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetOldestWaitingCall(ctx context.Context, companyID int32) (CallQueue, error) {
	row := q.db.QueryRowContext(ctx, getOldestWaitingCall, companyID)
	var i CallQueue
	err := row.Scan(
		&i.ID,
		&i.CallSid,
		&i.CompanyID,
		&i.FromNumber,
		&i.ToNumber,
		&i.Status,
		&i.CurrentAgentIndex,
		&i.AgentsTried,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutstandingTasksCount = `-- name: GetOutstandingTasksCount :one
SELECT
    COUNT(*) as task_count
FROM tasks
WHERE assigned_to = ? AND status != 'completed'
`

func (q *Queries) GetOutstandingTasksCount(ctx context.Context, assignedTo int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOutstandingTasksCount, assignedTo)
	var task_count int64
	err := row.Scan(&task_count)
	return task_count, err
}

const getOverdueTasksCount = `-- name: GetOverdueTasksCount :one
SELECT
    COUNT(*) as task_count
FROM tasks
WHERE assigned_to = ? AND status != 'completed' AND due_date IS NOT NULL AND due_date < NOW()
`

func (q *Queries) GetOverdueTasksCount(ctx context.Context, assignedTo int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOverdueTasksCount, assignedTo)
	var task_count int64
	err := row.Scan(&task_count)
	return task_count, err
}

const getPendingTasksByUser = `-- name: GetPendingTasksByUser :many
SELECT id, assigned_to, customer_id, call_id, title, description, type, status, due_date, created_at FROM tasks
WHERE assigned_to = ? AND status = 'pending'
ORDER BY due_date ASC
`

func (q *Queries) GetPendingTasksByUser(ctx context.Context, assignedTo int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTasksByUser, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.AssignedTo,
			&i.CustomerID,
			&i.CallID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueueEntry = `-- name: GetQueueEntry :one
SELECT id, call_sid, company_id, from_number, to_number, status, current_agent_index, agents_tried, created_at, updated_at FROM call_queue WHERE call_sid = ?
`

func (q *Queries) GetQueueEntry(ctx context.Context, callSid string) (CallQueue, error) {
	row := q.db.QueryRowContext(ctx, getQueueEntry, callSid)
	var i CallQueue
	err := row.Scan(
		&i.ID,
		&i.CallSid,
		&i.CompanyID,
		&i.FromNumber,
		&i.ToNumber,
		&i.Status,
		&i.CurrentAgentIndex,
		&i.AgentsTried,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, created_at, expires_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, assigned_to, customer_id, call_id, title, description, type, status, due_date, created_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.AssignedTo,
		&i.CustomerID,
		&i.CallID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskStats = `-- name: GetTaskStats :one
SELECT
    COUNT(*) as total_tasks,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_tasks,
    COUNT(CASE WHEN status = 'in_progress' THEN 1 END) as in_progress_tasks,
    COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_tasks,
    COUNT(CASE WHEN type = 'follow-up' THEN 1 END) as follow_up_tasks,
    COUNT(CASE WHEN type = 'callback' THEN 1 END) as callback_tasks,
    COUNT(CASE WHEN status != 'completed' AND due_date IS NOT NULL AND due_date < NOW() THEN 1 END) as overdue_tasks
FROM tasks
WHERE assigned_to = ?
`

type GetTaskStatsRow struct {
	TotalTasks      int64 `json:"total_tasks"`
	PendingTasks    int64 `json:"pending_tasks"`
	InProgressTasks int64 `json:"in_progress_tasks"`
	CompletedTasks  int64 `json:"completed_tasks"`
	FollowUpTasks   int64 `json:"follow_up_tasks"`
	CallbackTasks   int64 `json:"callback_tasks"`
	OverdueTasks    int64 `json:"overdue_tasks"`
}

func (q *Queries) GetTaskStats(ctx context.Context, assignedTo int32) (GetTaskStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskStats, assignedTo)
	var i GetTaskStatsRow
	err := row.Scan(
		&i.TotalTasks,
		&i.PendingTasks,
		&i.InProgressTasks,
		&i.CompletedTasks,
		&i.FollowUpTasks,
		&i.CallbackTasks,
		&i.OverdueTasks,
	)
	return i, err
}

const getTaskStatsByStatus = `-- name: GetTaskStatsByStatus :one
SELECT
    COUNT(*) as task_count
FROM tasks
WHERE assigned_to = ? AND status = ?
`

type GetTaskStatsByStatusParams struct {
	AssignedTo int32          `json:"assigned_to"`
	Status     sql.NullString `json:"status"`
}

func (q *Queries) GetTaskStatsByStatus(ctx context.Context, arg GetTaskStatsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTaskStatsByStatus, arg.AssignedTo, arg.Status)
	var task_count int64
	err := row.Scan(&task_count)
	return task_count, err
}

const getTaskStatsByType = `-- name: GetTaskStatsByType :one
SELECT
    COUNT(*) as task_count
FROM tasks
WHERE assigned_to = ? AND type = ?
`

type GetTaskStatsByTypeParams struct {
	AssignedTo int32          `json:"assigned_to"`
	Type       sql.NullString `json:"type"`
}

func (q *Queries) GetTaskStatsByType(ctx context.Context, arg GetTaskStatsByTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTaskStatsByType, arg.AssignedTo, arg.Type)
	var task_count int64
	err := row.Scan(&task_count)
	return task_count, err
}

const getTasksByCustomer = `-- name: GetTasksByCustomer :many
SELECT id, assigned_to, customer_id, call_id, title, description, type, status, due_date, created_at FROM tasks
WHERE customer_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetTasksByCustomer(ctx context.Context, customerID sql.NullInt32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.AssignedTo,
			&i.CustomerID,
			&i.CallID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByUser = `-- name: GetTasksByUser :many
SELECT id, assigned_to, customer_id, call_id, title, description, type, status, due_date, created_at FROM tasks
WHERE assigned_to = ?
ORDER BY created_at DESC
`

func (q *Queries) GetTasksByUser(ctx context.Context, assignedTo int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByUser, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.AssignedTo,
			&i.CustomerID,
			&i.CallID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksDueInNext7Days = `-- name: GetTasksDueInNext7Days :one
SELECT
    COUNT(*) as task_count
FROM tasks
WHERE assigned_to = ?
    AND status != 'completed'
    AND due_date IS NOT NULL
    AND due_date >= NOW()
    AND due_date <= DATE_ADD(NOW(), INTERVAL 7 DAY)
`

func (q *Queries) GetTasksDueInNext7Days(ctx context.Context, assignedTo int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTasksDueInNext7Days, assignedTo)
	var task_count int64
	err := row.Scan(&task_count)
	return task_count, err
}

const getTasksDueToday = `-- name: GetTasksDueToday :one
SELECT
    COUNT(*) as task_count
FROM tasks
WHERE assigned_to = ? AND DATE(due_date) = CURDATE() AND status != 'completed'
`

func (q *Queries) GetTasksDueToday(ctx context.Context, assignedTo int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTasksDueToday, assignedTo)
	var task_count int64
	err := row.Scan(&task_count)
	return task_count, err
}

const getTodayCallStats = `-- name: GetTodayCallStats :one
SELECT
    COUNT(*) as total_calls,
    COUNT(CASE WHEN call_status = 'completed' THEN 1 END) as answered_calls,
    COUNT(CASE WHEN call_status IN ('no-answer', 'busy', 'failed') THEN 1 END) as missed_calls,
    COALESCE(AVG(CASE WHEN duration > 0 THEN duration END), 0) as avg_duration
FROM transcriptions
WHERE agent_id = ?
    AND DATE(created_at) = CURDATE()
`

type GetTodayCallStatsRow struct {
	TotalCalls    int64       `json:"total_calls"`
	AnsweredCalls int64       `json:"answered_calls"`
	MissedCalls   int64       `json:"missed_calls"`
	AvgDuration   interface{} `json:"avg_duration"`
}

func (q *Queries) GetTodayCallStats(ctx context.Context, agentID sql.NullInt32) (GetTodayCallStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTodayCallStats, agentID)
	var i GetTodayCallStatsRow
	err := row.Scan(
		&i.TotalCalls,
		&i.AnsweredCalls,
		&i.MissedCalls,
		&i.AvgDuration,
	)
	return i, err
}

const getUserByAgentID = `-- name: GetUserByAgentID :one
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, last_call_ended_at, created_at FROM users WHERE agent_id = ?
`

func (q *Queries) GetUserByAgentID(ctx context.Context, agentID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAgentID, agentID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.LastCallEndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, last_call_ended_at, created_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.LastCallEndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, firstname, lastname, agent_id, company_id, last_call_ended_at, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Firstname,
		&i.Lastname,
		&i.AgentID,
		&i.CompanyID,
		&i.LastCallEndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidOTPCode = `-- name: GetValidOTPCode :one
SELECT id, email, otp_code, expires_at, used, created_at FROM otp_codes
WHERE email = ? AND otp_code = ? AND used = 0 AND expires_at > NOW()
ORDER BY created_at DESC LIMIT 1
`

type GetValidOTPCodeParams struct {
	Email   string `json:"email"`
	OtpCode string `json:"otp_code"`
}

func (q *Queries) GetValidOTPCode(ctx context.Context, arg GetValidOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRowContext(ctx, getValidOTPCode, arg.Email, arg.OtpCode)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OtpCode,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitingCallsByCompany = `-- name: GetWaitingCallsByCompany :many
SELECT id, call_sid, company_id, from_number, to_number, status, current_agent_index, agents_tried, created_at, updated_at FROM call_queue
WHERE company_id = ? AND status = 'waiting'
ORDER BY created_at ASC
`

func (q *Queries) GetWaitingCallsByCompany(ctx context.Context, companyID int32) ([]CallQueue, error) {
	rows, err := q.db.QueryContext(ctx, getWaitingCallsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallQueue{}
	for rows.Next() {
		var i CallQueue
		if err := rows.Scan(
			&i.ID,
			&i.CallSid,
			&i.CompanyID,
			&i.FromNumber,
			&i.ToNumber,
			&i.Status,
			&i.CurrentAgentIndex,
			&i.AgentsTried,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOTPCodeAsUsed = `-- name: MarkOTPCodeAsUsed :exec
UPDATE otp_codes SET used = 1 WHERE id = ?
`

func (q *Queries) MarkOTPCodeAsUsed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markOTPCodeAsUsed, id)
	return err
}

const markQueueEntryAbandoned = `-- name: MarkQueueEntryAbandoned :exec
UPDATE call_queue SET status = 'abandoned', updated_at = NOW() WHERE call_sid = ?
`

func (q *Queries) MarkQueueEntryAbandoned(ctx context.Context, callSid string) error {
	_, err := q.db.ExecContext(ctx, markQueueEntryAbandoned, callSid)
	return err
}

const markQueueEntryConnected = `-- name: MarkQueueEntryConnected :exec
UPDATE call_queue SET status = 'connected', updated_at = NOW() WHERE call_sid = ?
`

func (q *Queries) MarkQueueEntryConnected(ctx context.Context, callSid string) error {
	_, err := q.db.ExecContext(ctx, markQueueEntryConnected, callSid)
	return err
}

const markQueueEntryRouting = `-- name: MarkQueueEntryRouting :exec
UPDATE call_queue SET status = 'routing', updated_at = NOW() WHERE call_sid = ?
`

func (q *Queries) MarkQueueEntryRouting(ctx context.Context, callSid string) error {
	_, err := q.db.ExecContext(ctx, markQueueEntryRouting, callSid)
	return err
}

const updateCallRecord = `-- name: UpdateCallRecord :exec
UPDATE transcriptions
SET call_status = ?, duration = ?
WHERE call_sid = ?
`

type UpdateCallRecordParams struct {
	CallStatus sql.NullString `json:"call_status"`
	Duration   sql.NullInt32  `json:"duration"`
	CallSid    string         `json:"call_sid"`
}

func (q *Queries) UpdateCallRecord(ctx context.Context, arg UpdateCallRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateCallRecord, arg.CallStatus, arg.Duration, arg.CallSid)
	return err
}

const updateQueueEntry = `-- name: UpdateQueueEntry :exec
UPDATE call_queue
SET status = ?, current_agent_index = ?, agents_tried = ?, updated_at = NOW()
WHERE call_sid = ?
`

type UpdateQueueEntryParams struct {
	Status            sql.NullString `json:"status"`
	CurrentAgentIndex sql.NullInt32  `json:"current_agent_index"`
	AgentsTried       sql.NullString `json:"agents_tried"`
	CallSid           string         `json:"call_sid"`
}

func (q *Queries) UpdateQueueEntry(ctx context.Context, arg UpdateQueueEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateQueueEntry,
		arg.Status,
		arg.CurrentAgentIndex,
		arg.AgentsTried,
		arg.CallSid,
	)
	return err
}

const updateQueueStatus = `-- name: UpdateQueueStatus :exec
UPDATE call_queue SET status = ?, updated_at = NOW() WHERE call_sid = ?
`

type UpdateQueueStatusParams struct {
	Status  sql.NullString `json:"status"`
	CallSid string         `json:"call_sid"`
}

func (q *Queries) UpdateQueueStatus(ctx context.Context, arg UpdateQueueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateQueueStatus, arg.Status, arg.CallSid)
	return err
}

const updateUserLastCallEnded = `-- name: UpdateUserLastCallEnded :exec
UPDATE users SET last_call_ended_at = ? WHERE id = ?
`

type UpdateUserLastCallEndedParams struct {
	LastCallEndedAt sql.NullTime `json:"last_call_ended_at"`
	ID              int32        `json:"id"`
}

func (q *Queries) UpdateUserLastCallEnded(ctx context.Context, arg UpdateUserLastCallEndedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastCallEnded, arg.LastCallEndedAt, arg.ID)
	return err
}
