// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type CallTranscription struct {
	ID         int64          `json:"id"`
	CustomerID int64          `json:"customer_id"`
	AgentID    int64          `json:"agent_id"`
	CallSid    sql.NullString `json:"call_sid"`
	Transcript string         `json:"transcript"`
	Summary    sql.NullString `json:"summary"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Company struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Customer struct {
	ID                 int64          `json:"id"`
	CompanyID          int64          `json:"company_id"`
	FirstName          string         `json:"first_name"`
	LastName           string         `json:"last_name"`
	Email              sql.NullString `json:"email"`
	Phone              sql.NullString `json:"phone"`
	MedicalAidProvider sql.NullString `json:"medical_aid_provider"`
	MedicalAidNumber   sql.NullString `json:"medical_aid_number"`
	MedicalPlan        sql.NullString `json:"medical_plan"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

type CustomerPremium struct {
	ID            int64        `json:"id"`
	CustomerID    int64        `json:"customer_id"`
	PremiumAmount float64      `json:"premium_amount"`
	EffectiveDate time.Time    `json:"effective_date"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Firstname    string       `json:"firstname"`
	Lastname     string       `json:"lastname"`
	AgentID      string       `json:"agent_id"`
	CompanyID    int64        `json:"company_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
